Update to 1.21.3
Greeenman999/LibrarianTradeFinder pull request #67
Opened 2024-11-08 21:41 UTC by thepapanoob

Hello Greenman999,

ive updated the mod to 1.21.3 (had to update gradle aswell)
everything seems to be working great.

Sincerely,
Papanoob

2024-11-16 17:36 UTC, ticua07 commented
Does work in 1.21.3, tested it by manually building the mod and using the Fabulously Optimized modpack.

You forgot to bump the version from 2.2.3 to 2.2.4 in the gradle.properties file

2024-11-24 19:49 UTC, thepapanoob commented
oh yea good catch forgot to update the version... but yes its working on 1.21.3 im using it myself :)

2024-11-26 17:03 UTC, Greeenman999 requested changes

2024-11-26 17:04 UTC, Greeenman999 commented
Thanks for your work! Will merge if you update the version :) Thanks!

2024-11-30 17:38 UTC, Greeenman999 approved these changes

2024-11-30 17:41 UTC, merged